import os
os.system("sudo apt-get install python-pip")
os.system("sudo apt-get install python3-pip")
os.system("sudo apt-get install pip3")
os.system("sudo apt-get install pip")
os.system("pip install hashlib")
os.system("pip install passlib")
os.system("pip install requests")
os.system("pip install subprocess")
os.system("pip install colorama")
os.system("pip install json")
os.system("pip install base64")
os.system("pip3 install hashlib")
os.system("pip3 install passlib")
os.system("pip3 install requests")
os.system("pip3 install subprocess")
os.system("pip3 install colorama")
os.system("pip3 install json")
os.system("pip3 install base64")
